host = "localhost"
port = 3000
path = "http://localhost:3000"
static_path = "http://localhost:3000/static"

[mysql]
host = "localhost"
port = 3306
user = "root"
password = "111111"
db_name = "runner"

[redis]
protocol = "redis"
host = "localhost"

