host = "localhost"
port = 3000
path = "http://localhost:3000"
static_path = "http://localhost:3000/static"

[mysql]
host = "localhost"
port = 3306
user = "root"
password = "111111"
db_name = "runner"

[redis]
protocol = "redis"
host = "localhost"

[github]
client_id = "c28f7718a19ee09c4a71"
client_secret = "df1380ad7e8bbee69bff50d9671aac2a7f1a31b8"

